import { appendExchangeEvent, getExchangeAdmin } from './server'
import { evaluateProposal, mergeExchangePolicy } from '@/exchange-gateway/src/policy'
import { buildCommitmentDraft } from '@/exchange-gateway/src/draft'
import { finalizeCommitment } from '@/exchange-gateway/src/commitment'
import type { Consideration, ProposalAuthority, StewardDecision } from '@/exchange-gateway/src/types'

type CompanyRow={id:string;domain:string;categories?:string[]|null;agent_mode?:string|null;exchange_agent_endpoint?:string|null;exchange_policy?:unknown}
export type TriageInput={category:string;consideration:Consideration[];requiredAuthorization:ProposalAuthority}
export function companyPolicy(company:CompanyRow){return mergeExchangePolicy(company.exchange_policy,company.categories??[])}

export async function notifyDomainAgent(company:CompanyRow,event:Record<string,unknown>){if(!company.exchange_agent_endpoint)return{delivered:false,reason:'no_endpoint'};try{const response=await fetch(company.exchange_agent_endpoint,{method:'POST',headers:{'content-type':'application/json','user-agent':'Contribution-Exchange/0.2'},body:JSON.stringify({protocol:'Contribution Exchange',version:'0.2',...event}),signal:AbortSignal.timeout(5000)});return{delivered:response.ok,status:response.status}}catch(error){return{delivered:false,reason:error instanceof Error?error.message:'delivery_failed'}}}

export async function dispatchToDomainAgent(input:{company:CompanyRow;exchange:{id:string;public_id:string;state:string;title:string;target_domain:string};triage:TriageInput;eventType:'proposal_received'|'request_received'}):Promise<{mode:string;decision?:StewardDecision;delivery?:Record<string,unknown>}>{const{company,exchange,triage,eventType}=input;const admin=getExchangeAdmin();const mode=company.agent_mode||'hosted_steward';const controlBase=process.env.NEXT_PUBLIC_SITE_URL??'https://signalaf.com';if(mode==='bring_your_own'){const delivery=await notifyDomainAgent(company,{event:eventType,exchange_id:exchange.public_id,domain:exchange.target_domain,state:exchange.state,title:exchange.title,fetch:`${controlBase}/api/exchange/exchanges/${encodeURIComponent(exchange.public_id)}`,note:'Treat this push as a notification. Authenticate back to the Exchange control plane before reading non-public details or taking action.'});await admin.from('exchange_records').update({steward_status:delivery.delivered?'delivered_to_byo':'failed',updated_at:new Date().toISOString()}).eq('id',exchange.id);await appendExchangeEvent({exchangeId:exchange.id,eventType:'domain_agent_delivery',actor:{type:'system',id:'exchange-router'},fromState:'proposed',toState:'proposed',payload:{mode,...delivery}});return{mode,delivery}}if(mode==='passive'){await admin.from('exchange_records').update({escalation_required:true,escalation_reasons:['domain agent is passive'],steward_status:'escalated',updated_at:new Date().toISOString()}).eq('id',exchange.id);await appendExchangeEvent({exchangeId:exchange.id,eventType:'steward_escalation_required',actor:{type:'system',id:'exchange-steward'},fromState:'proposed',toState:'proposed',payload:{reasons:['domain agent is passive']}});return{mode}}
  const policy=companyPolicy(company);const decision=evaluateProposal({policy,category:triage.category,consideration:triage.consideration,requiredAuthorization:triage.requiredAuthorization});if(decision.disposition==='engage'){const {data:full}=await admin.from('exchange_records').select('*').eq('id',exchange.id).single();const draft=finalizeCommitment(buildCommitmentDraft(full||exchange));const companyAcceptance=policy.human_required_for_commitment?{}:{company:{terms_hash:draft.provenance.terms_hash,accepted_at:new Date().toISOString(),accepted_by:'hosted_steward'}};await admin.from('exchange_records').update({state:'negotiating',commitment:draft,terms_hash:draft.provenance.terms_hash,commitment_acceptances:companyAcceptance,steward_status:'engaged',escalation_required:false,escalation_reasons:[],updated_at:new Date().toISOString()}).eq('id',exchange.id);await appendExchangeEvent({exchangeId:exchange.id,eventType:'steward_engaged',actor:{type:'agent',id:`domain-agent:${company.domain}`},fromState:'proposed',toState:'engaged',payload:{response:decision.response}});await appendExchangeEvent({exchangeId:exchange.id,eventType:'steward_terms_drafted',actor:{type:'agent',id:`domain-agent:${company.domain}`},fromState:'engaged',toState:'negotiating',payload:{terms_hash:draft.provenance.terms_hash,principal_acceptance_required:policy.human_required_for_commitment}})}else{await admin.from('exchange_records').update({steward_status:'escalated',escalation_required:true,escalation_reasons:decision.reasons,updated_at:new Date().toISOString()}).eq('id',exchange.id);await appendExchangeEvent({exchangeId:exchange.id,eventType:'steward_escalation_required',actor:{type:'agent',id:`domain-agent:${company.domain}`},fromState:'proposed',toState:'proposed',payload:{response:decision.response,reasons:decision.reasons}})}return{mode,decision}}
