/**
 * app/metrics/compression-ratio/page.tsx — "Compression Ratio — Output per Input"
 *
 * Defines the compression ratio metric: how much output you get back per token
 * of fresh input sent. A foundational ratio that feeds into the headline yield.
 *
 * JSON-LD: breadcrumb + definedTerm + faqPage.
 */

import type { Metadata } from "next";
import Link from "next/link";
import { withOG } from "@/lib/seo";
import { WaveHero } from "@/components/ui/WaveHero";
import { JsonLd } from "@/components/seo/JsonLd";
import { breadcrumb, definedTerm, faqPage } from "@/lib/jsonld";

export const metadata: Metadata = withOG({
  title: "Compression Ratio — Output per Input",
  description:
    "Compression ratio = output / input \u2014 how much you get back per token sent to an AI model. Learn what it means and how to improve it.",
  path: "/metrics/compression-ratio",
});

export default function CompressionRatioPage() {
  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-8 py-2">
      <JsonLd
        data={[
          breadcrumb([
            { name: "Metrics", path: "/metrics" },
            { name: "Compression Ratio", path: "/metrics/compression-ratio" },
          ]),
          definedTerm(
            "Compression Ratio — Output per Input",
            "Compression Ratio = output / input. The ratio of tokens generated by the model to fresh input tokens sent by the operator. High ratio means efficient prompting — you get a lot back per token invested. Low ratio means verbose inputs with little return.",
            "/metrics/compression-ratio",
          ),
          faqPage([
            {
              question: "What is the token compression ratio in AI coding?",
              answer:
                "Compression Ratio = output / input. It measures how many tokens the model generates for every token of fresh input you send. A ratio of 3 means you get 3 output tokens per 1 input token. High ratios indicate efficient prompting; low ratios indicate verbose inputs with little return.",
            },
            {
              question: "What is a good compression ratio for AI coding?",
              answer:
                "It depends on the task. Code generation tasks tend to produce higher ratios (you describe what you want, the model writes substantial code). Debugging or review tasks may produce lower ratios (you paste a lot of context, the model gives a short diagnosis). The key is tracking your ratio over time and noticing when it drops — that usually means your inputs are getting verbose without proportional output.",
            },
            {
              question: "How is compression ratio different from yield?",
              answer:
                "Compression ratio = output / input. Yield (Υ) = (cache_read × output) / input². Compression ratio captures one dimension (output per input) while yield captures three (output, input economy, and cache reuse). An operator can have a high compression ratio but low yield if they never reuse cached context. Yield is the headline metric; compression ratio is a component.",
            },
            {
              question: "Can a compression ratio be too high?",
              answer:
                "A very high ratio with low absolute output can be misleading. Sending 10 input tokens and getting 30 output tokens gives a ratio of 3, but 30 output tokens may not be enough to be useful. Compression ratio is most meaningful alongside absolute output volume and yield — not in isolation.",
            },
          ]),
        ]}
      />

      <WaveHero
        eyebrow="◈ Foundational Metric"
        terminalText="RATIO"
        title="Compression Ratio — Output per Input"
        subtitle={
          <>
            How much you get back per token you send. The{" "}
            <span className="text-gold">output-to-input ratio</span> at the
            heart of efficient prompting.
          </>
        }
      />

      {/* ── The formula ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          The compression ratio formula
        </h2>
        <div className="rounded-lg border border-bg-border bg-bg-surface p-6">
          <p className="text-center font-mono text-2xl text-gold">
            Compression Ratio = output / input
          </p>
        </div>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          The compression ratio is the simplest meaningful token metric: divide
          what the model gave you (
          <strong className="text-text-primary">output</strong>) by what you
          sent it (<strong className="text-text-primary">input</strong>). A
          ratio of 1 means you got back exactly as many tokens as you sent. A
          ratio above 1 means the model expanded your input into more output
          than you provided. A ratio below 1 means you sent more than you got
          back — your input was &ldquo;compressed&rdquo; into a smaller
          response.
        </p>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          Note: <strong className="text-text-primary">input</strong> here refers
          to fresh input tokens only — not cached tokens. Cached context
          (cache_read) is reused from prior turns and doesn&rsquo;t count
          against your input investment. This is what makes the compression
          ratio a measure of <em>prompting efficiency</em> rather than total
          context size.
        </p>
      </section>

      {/* ── What it measures ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          What compression ratio measures
        </h2>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          The compression ratio measures how much value you extract per token of
          fresh input. It answers a simple question:{" "}
          <em>
            for every token I invest in typing or pasting, how many tokens of
            useful output do I get back?
          </em>
        </p>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          This is fundamentally a measure of{" "}
          <strong className="text-text-primary">prompting efficiency</strong>.
          An operator who writes a concise, well-structured prompt that elicits
          a long, useful response has a high ratio. An operator who pastes an
          entire file, adds rambling instructions, and gets back a one-line
          answer has a low ratio.
        </p>
      </section>

      {/* ── Why it matters ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          Why it matters
        </h2>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          Fresh input tokens are the most expensive part of the cascade. They
          cost full price to process, they&rsquo;re sent from scratch every
          turn, and — in the yield formula — they appear squared in the
          denominator. Every fresh input token you send without proportional
          output is pure waste.
        </p>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          The compression ratio makes that waste visible. If your ratio is
          trending down over a session, it usually means one of two things: your
          inputs are getting verbose (you&rsquo;re re-explaining context
          that&rsquo;s already in cache), or your prompts are too vague (the
          model is giving short, uncommitted responses because it doesn&rsquo;t
          know what you want).
        </p>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          Tracking compression ratio over time reveals your prompting habits.
          The goal isn&rsquo;t to maximize it in isolation — a ratio of 10 from
          a 5-token prompt that produces 50 useless tokens is worse than a ratio
          of 2 from a 500-token prompt that produces 1,000 high-value tokens.
          But as a diagnostic, it&rsquo;s the fastest way to spot input bloat.
        </p>
      </section>

      {/* ── High vs low ratio ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          High ratio vs low ratio
        </h2>
        <div className="rounded-lg border border-bg-border bg-bg-surface p-5">
          <p className="font-mono text-xs uppercase tracking-[0.14em] text-gold">
            High ratio — efficient prompting
          </p>
          <p className="mt-2 font-sans text-sm leading-relaxed text-text-secondary">
            You send concise, targeted inputs and the model responds with
            substantial, useful output. Your prompts are well-structured: clear
            intent, minimal redundancy, no unnecessary context. This is the
            signature of an operator who knows exactly what to ask and how to
            ask it.
          </p>
        </div>
        <div className="rounded-lg border border-bg-border bg-bg-surface p-5">
          <p className="font-mono text-xs uppercase tracking-[0.14em] text-text-muted">
            Low ratio — verbose inputs, little return
          </p>
          <p className="mt-2 font-sans text-sm leading-relaxed text-text-secondary">
            You send large inputs — pasted files, rambling instructions,
            redundant context — and get back relatively little. The model is
            spending its capacity processing your input rather than generating
            output. This often means your prompts lack focus or you&rsquo;re
            re-sending context that&rsquo;s already cached.
          </p>
        </div>
      </section>

      {/* ── Relationship to yield ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          Relationship to yield
        </h2>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          Compression ratio is a <em>component</em> of yield. Yield (Υ) =
          (cache_read × output) / input² can be rewritten as Υ = cache_read ×
          (output / input) / input = cache_read × compression_ratio / input. So
          yield is your compression ratio amplified by cache reuse and divided
          by input size.
        </p>
        <p className="font-sans text-sm leading-relaxed text-text-secondary">
          This means you can have a high compression ratio but still score low
          on yield if you don&rsquo;t reuse cached context. The compression
          ratio tells you your prompting is efficient; yield tells you your{" "}
          <em>overall cascade</em> is efficient. Both matter — but yield is the
          headline.
        </p>
      </section>

      {/* ── How to improve ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">
          How to improve your compression ratio
        </h2>
        <ul className="flex flex-col gap-3 font-sans text-sm leading-relaxed text-text-secondary">
          <li className="rounded-lg border border-bg-border-subtle bg-bg-surface p-4">
            <strong className="text-gold">
              1. Be specific about what you want.
            </strong>{" "}
            Vague prompts (&ldquo;help me with this code&rdquo;) produce short,
            non-committal responses. Specific prompts (&ldquo;write a TypeScript
            function that takes a URL string and returns the query params as a
            Record&lt;string, string&gt;&rdquo;) produce substantial, targeted
            output.
          </li>
          <li className="rounded-lg border border-bg-border-subtle bg-bg-surface p-4">
            <strong className="text-gold">
              2. Don&rsquo;t re-paste cached context.
            </strong>{" "}
            If the model already has a file in its context window from a prior
            turn, don&rsquo;t paste it again. Reference it: &ldquo;in the file
            we discussed earlier, add error handling to the fetch
            function.&rdquo; This keeps fresh input small while the model works
            from cache.
          </li>
          <li className="rounded-lg border border-bg-border-subtle bg-bg-surface p-4">
            <strong className="text-gold">
              3. Ask for complete deliverables.
            </strong>{" "}
            &ldquo;Write the full module&rdquo; produces more output than
            &ldquo;what&rsquo;s wrong with line 42?&rdquo; When the task allows
            it, request complete artifacts — functions, tests, documentation —
            rather than snippets or diagnostics.
          </li>
          <li className="rounded-lg border border-bg-border-subtle bg-bg-surface p-4">
            <strong className="text-gold">
              4. Trim boilerplate from your prompts.
            </strong>{" "}
            Remove pleasantries, redundant instructions, and context the model
            can infer. Every token you cut from input that doesn&rsquo;t reduce
            output raises your ratio.
          </li>
          <li className="rounded-lg border border-bg-border-subtle bg-bg-surface p-4">
            <strong className="text-gold">
              5. Use file references over inline code.
            </strong>{" "}
            In tools like Claude Code or Cursor, referencing a file path is
            cheaper than pasting its contents. The model reads the file from its
            context without you spending fresh input tokens on the content.
          </li>
        </ul>
      </section>

      {/* ── FAQ ── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-base font-bold text-text-primary">FAQ</h2>
        <dl className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              What is the token compression ratio in AI coding?
            </dt>
            <dd className="font-sans text-sm leading-relaxed text-text-secondary">
              Compression Ratio = output / input. It measures how many tokens
              the model generates for every token of fresh input you send. A
              ratio of 3 means you get 3 output tokens per 1 input token. High
              ratios indicate efficient prompting; low ratios indicate verbose
              inputs with little return.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              What is a good compression ratio for AI coding?
            </dt>
            <dd className="font-sans text-sm leading-relaxed text-text-secondary">
              It depends on the task. Code generation tends to produce higher
              ratios; debugging or review tasks may produce lower ratios. Track
              your ratio over time — a downward trend usually means your inputs
              are getting verbose without proportional output.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              How is compression ratio different from yield?
            </dt>
            <dd className="font-sans text-sm leading-relaxed text-text-secondary">
              Compression ratio = output / input captures one dimension. Yield
              (Υ) = (cache_read × output) / input² captures three: output, input
              economy, and cache reuse. You can have a high compression ratio
              but low yield if you never reuse cached context. Yield is the
              headline; compression ratio is a component.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              Can a compression ratio be too high?
            </dt>
            <dd className="font-sans text-sm leading-relaxed text-text-secondary">
              A very high ratio with low absolute output can be misleading.
              Sending 10 tokens and getting 30 back gives a ratio of 3, but 30
              tokens may not be useful. Compression ratio is most meaningful
              alongside absolute output volume and yield — not in isolation.
            </dd>
          </div>
        </dl>
      </section>

      {/* ── Cross-links ── */}
      <section className="mt-4 border-t border-bg-border-subtle pt-6">
        <p className="font-sans text-sm text-text-muted">
          Related metrics:{" "}
          <Link
            href="/metrics/yield-cascade"
            className="text-gold underline underline-offset-2"
          >
            Yield (Υ)
          </Link>
          {" · "}
          <Link
            href="/metrics/signal-to-noise-ratio"
            className="text-gold underline underline-offset-2"
          >
            Signal-to-Noise Ratio
          </Link>
          {" · "}
          <Link
            href="/metrics/velocity"
            className="text-gold underline underline-offset-2"
          >
            Velocity
          </Link>
          {" · "}
          <Link
            href="/methodology"
            className="text-gold underline underline-offset-2"
          >
            Methodology
          </Link>
        </p>
      </section>
    </div>
  );
}
