/**
 * app/privacy-preserving-ai-telemetry/page.tsx — Privacy & Security portal.
 *
 * The canonical public privacy/security portal for SigRank. Consolidates the
 * Upsilon Privacy Model, Data Policy, Consent Model, Data Retention, and
 * Opt-Out Policy into a single RSC page. Token counts only — never prompts.
 *
 * JSON-LD: Breadcrumb + FAQPage.
 */

import type { Metadata } from "next";
import Link from "next/link";
import { withOG } from "@/lib/seo";
import { WaveHero } from "@/components/ui/WaveHero";
import { JsonLd } from "@/components/seo/JsonLd";
import { breadcrumb, faqPage } from "@/lib/jsonld";

export const metadata: Metadata = withOG({
  title: "Privacy-Preserving AI Telemetry \u2014 SigRank",
  description:
    "SigRank collects token counts only \u2014 never prompts, code, or conversation text. Four token pillars, ed25519-signed, server-side rescoring, replay protection, and plausibility gates. The canonical privacy & security portal.",
  path: "/privacy-preserving-ai-telemetry",
});

// ISR: revalidate daily. Privacy policy content changes rarely.
export const revalidate = 86400;

const FAQS = [
  {
    question: "Does SigRank read my prompts or conversation content?",
    answer:
      "No. The on-device scanner reads four token counts only \u2014 input, output, cache_read, and cache_create. No prompts, code, file contents, tool calls, or conversation text are ever transmitted, read, or stored by the SigRank service.",
  },
  {
    question: "What data leaves my machine when I submit a snapshot?",
    answer:
      "Only four integer token counts (input, output, cache_read, cache_create) plus submission metadata, the device public key, codename, window, and an ed25519 signature. The server verifies the signature and recomputes all derived metrics without ever seeing your data.",
  },
  {
    question: "Can I delete my data or opt out of collection?",
    answer:
      "Yes. SignalAF provides three distinct choices: pause collection (stop future submissions, preserve history), delete history (remove telemetry and derived data), and delete account (remove the account link and associated data). Until Phase 5 controls are deployed, use the removal contact path.",
  },
  {
    question: "How does SigRank prevent leaderboard gaming?",
    answer:
      "Every snapshot is ed25519-signed by a device-bound key. The server recomputes all derived metrics from the four raw token pillars \u2014 operators cannot submit inflated values directly. Replay protection blocks resubmission, plausibility gates flag implausible ratios, and Benford\u2019s Law analysis detects statistical anomalies.",
  },
  {
    question: "Is the optional sigrank proxy a submission path?",
    answer:
      "No. The optional sigrank proxy is a local loopback transport path to Anthropic or OpenAI, not a submission path to the SigRank leaderboard. When explicitly enabled, it necessarily receives and forwards provider-bound API keys, prompts, and responses in memory, but it does not persist that content or send it to the SigRank service \u2014 only provider-reported token counts are appended to a local file.",
  },
];

export default function PrivacyPreservingAITelemetryPage() {
  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-8 py-2">
      <JsonLd
        data={[
          breadcrumb([
            { name: "Privacy-Preserving AI Telemetry", path: "/privacy-preserving-ai-telemetry" },
          ]),
          faqPage(FAQS),
        ]}
      />

      <WaveHero
        eyebrow="◈ Privacy &amp; Security"
        terminalText="PRIVACY"
        title="Privacy-Preserving AI Telemetry"
        subtitle={
          <>
            SigRank collects{" "}
            <strong className="text-text-primary">token counts only</strong>{" "}
            — never prompts, code, or conversation text. Four integer pillars,
            cryptographically signed, verified server-side.
          </>
        }
      />

      {/* ── What leaves your machine ──────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          What leaves your machine
        </h2>
        <p className="text-base text-text-secondary">
          Every submission path sends only{" "}
          <strong className="text-text-primary">four numbers</strong>:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">Input tokens</strong> —
            fresh tokens sent to the model.
          </li>
          <li>
            <strong className="text-text-primary">Output tokens</strong> —
            tokens generated by the model.
          </li>
          <li>
            <strong className="text-text-primary">Cache create tokens</strong>{" "}
            — context written to cache.
          </li>
          <li>
            <strong className="text-text-primary">Cache read tokens</strong> —
            context reused from cache.
          </li>
        </ul>
        <p className="text-base text-text-secondary">
          That is the entire payload — no prompts, no code, no file contents,
          no conversation text. The on-device scanner parses your input
          locally and sends only the four token counts to the server, which
          re-parses and re-scores them authoritatively.
        </p>
        <p className="text-base text-text-secondary">
          The optional{" "}
          <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
            sigrank proxy
          </code>{" "}
          is a local loopback transport path to Anthropic or OpenAI, not a
          submission path to the SigRank leaderboard. When explicitly enabled,
          it necessarily receives and forwards provider-bound API keys,
          prompts, tool calls, and responses in memory. It does not persist
          that content or send it to the SigRank service; it appends only
          provider-reported token counts, model/backend metadata, and
          timestamps to{" "}
          <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
            ~/.sigrank-mcp/proxy-sessions.jsonl
          </code>
          .
        </p>
      </section>

      {/* ── What we collect ───────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          What we collect
        </h2>
        <p className="text-base text-text-secondary">
          SignalAF may receive the following data, collected only as needed to
          operate the service:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">
              Submission-window metadata
            </strong>{" "}
            — window type, timestamps, and submission context.
          </li>
          <li>
            <strong className="text-text-primary">
              Four raw token pillars
            </strong>{" "}
            — fresh input, output, cache_read, cache_create counts.
          </li>
          <li>
            <strong className="text-text-primary">
              Session/activity aggregates
            </strong>{" "}
            — per-session, per-platform token totals.
          </li>
          <li>
            <strong className="text-text-primary">
              Device and agent integrity material
            </strong>{" "}
            — public keys, agent identifiers, and verification artifacts.
          </li>
          <li>
            <strong className="text-text-primary">
              Signed snapshot data
            </strong>{" "}
            — ed25519 signatures and source attestations for audit.
          </li>
          <li>
            <strong className="text-text-primary">
              Account-to-operator links
            </strong>{" "}
            — the binding between a claimed operator and an account.
          </li>
        </ul>
        <p className="text-sm text-text-muted">
          Collection is not permission to repurpose data. New uses require a
          documented basis, minimization review, and any required renewed
          consent.
        </p>
      </section>

      {/* ── What we derive ────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          What we derive
        </h2>
        <p className="text-base text-text-secondary">
          The server recomputes all derived metrics from the four raw token
          pillars — operators cannot submit inflated values directly. Derived
          data remains conditional on its source window and method:
        </p>
        <div className="overflow-x-auto rounded-lg border border-bg-border bg-bg-surface">
          <table className="w-full border-collapse font-sans text-sm">
            <thead>
              <tr className="border-b border-bg-border bg-bg-elevated">
                <th className="px-4 py-2 text-left font-mono text-xs uppercase tracking-wide text-text-muted">
                  Metric
                </th>
                <th className="px-4 py-2 text-left font-mono text-xs uppercase tracking-wide text-text-muted">
                  Formula
                </th>
                <th className="px-4 py-2 text-left font-mono text-xs uppercase tracking-wide text-text-muted">
                  Meaning
                </th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-bg-border-subtle">
                <td className="px-4 py-2 text-text-primary">Yield (Υ)</td>
                <td className="px-4 py-2 font-mono text-gold">
                  cache_read × output / input²
                </td>
                <td className="px-4 py-2 text-text-secondary">
                  Token-cascade efficiency
                </td>
              </tr>
              <tr className="border-b border-bg-border-subtle">
                <td className="px-4 py-2 text-text-primary">SNR</td>
                <td className="px-4 py-2 font-mono text-gold">
                  output / (input + output)
                </td>
                <td className="px-4 py-2 text-text-secondary">
                  Output share of the direct exchange
                </td>
              </tr>
              <tr className="border-b border-bg-border-subtle">
                <td className="px-4 py-2 text-text-primary">Leverage</td>
                <td className="px-4 py-2 font-mono text-gold">
                  cache_read / input
                </td>
                <td className="px-4 py-2 text-text-secondary">
                  Cache reuse relative to fresh input
                </td>
              </tr>
              <tr className="border-b border-bg-border-subtle">
                <td className="px-4 py-2 text-text-primary">Velocity</td>
                <td className="px-4 py-2 font-mono text-gold">
                  output / input
                </td>
                <td className="px-4 py-2 text-text-secondary">
                  Output tokens per fresh input token
                </td>
              </tr>
              <tr>
                <td className="px-4 py-2 text-text-primary">10xDEV</td>
                <td className="px-4 py-2 font-mono text-gold">
                  log₁₀(cache_read / input)
                </td>
                <td className="px-4 py-2 text-text-secondary">
                  Log-scale Leverage
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="text-base text-text-secondary">
          The service also derives ranks, percentiles, verification tiers,
          integrity reasons, and field aggregates from these metrics.
        </p>
      </section>

      {/* ── What we never collect ─────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          What we never collect
        </h2>
        <p className="text-base text-text-secondary">
          The SigRank service cannot see:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">Prompts or messages</strong>{" "}
            — the words you send to the model.
          </li>
          <li>
            <strong className="text-text-primary">
              Code or file contents
            </strong>{" "}
            — nothing from your working directory.
          </li>
          <li>
            <strong className="text-text-primary">
              Tool calls or their results
            </strong>{" "}
            — agent actions and outputs.
          </li>
          <li>
            <strong className="text-text-primary">Conversation text</strong> —
            the full exchange history.
          </li>
          <li>
            <strong className="text-text-primary">
              Which AI platform you use
            </strong>{" "}
            — beyond token counts.
          </li>
          <li>
            <strong className="text-text-primary">Your identity</strong> —
            only your chosen codename.
          </li>
        </ul>
        <p className="text-base text-text-secondary">
          <strong className="text-text-primary">API keys</strong> are never
          collected by the submission path. The only exception is the optional{" "}
          <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
            sigrank proxy
          </code>
          , which — only when explicitly enabled — receives and forwards
          provider-bound API keys in memory to route traffic to Anthropic or
          OpenAI. That content is never persisted or sent to the SigRank
          service.
        </p>
      </section>

      {/* ── Consent model ─────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Consent model
        </h2>
        <p className="text-base text-text-secondary">
          Consent is captured at{" "}
          <strong className="text-text-primary">enrollment</strong>, before
          routine submission collection begins. The consent record includes:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>The timestamp of acceptance.</li>
          <li>The accepted terms version.</li>
          <li>The accepted privacy version.</li>
          <li>The action or interface that captured consent.</li>
          <li>The linked operator or account.</li>
        </ul>
        <p className="text-base text-text-secondary">
          Consent versions are{" "}
          <strong className="text-text-primary">
            immutable historical facts
          </strong>
          : accepting a later version appends or updates a new acceptance
          record; it does not make an earlier consent appear to have covered
          new terms. Materially changed purposes require renewed, explicit
          consent.
        </p>
        <p className="text-sm text-text-muted">
          Phase 1 status: this document defines the target model. The Phase 2
          checklist specifies planned{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            operators
          </code>{" "}
          fields (
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            consented_at
          </code>
          ,{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            terms_version
          </code>
          ,{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            privacy_version
          </code>
          ,{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            data_opt_out
          </code>
          ,{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            data_opt_out_at
          </code>
          ); do not assume they are enforced until the migration and
          application wiring land.
        </p>
      </section>

      {/* ── Data retention ────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Data retention
        </h2>
        <p className="text-base text-text-secondary">
          Retention is{" "}
          <strong className="text-text-primary">purpose-limited</strong>.
          Active account links, submissions, derived metrics, and integrity
          records are kept only while needed to operate the service, support
          reproducibility, prevent abuse, or meet documented legal
          obligations.
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">Paused collection:</strong>{" "}
            retain existing history under the selected account state until
            deletion, account closure, or the applicable schedule.
          </li>
          <li>
            <strong className="text-text-primary">History deletion:</strong>{" "}
            remove telemetry and derived history from active systems; retain
            only minimum deletion/audit evidence and security records where
            necessary.
          </li>
          <li>
            <strong className="text-text-primary">Account deletion:</strong>{" "}
            remove the account link and associated active data, subject to the
            same narrow exceptions.
          </li>
          <li>
            <strong className="text-text-primary">Backups:</strong> expire
            according to an operational backup schedule and are not a source
            for restoring deleted active records except under controlled,
            documented conditions.
          </li>
        </ul>
        <p className="text-sm text-text-muted">
          Specific durations must be published before enforcement. This Phase
          1 policy intentionally does not invent retention periods absent an
          approved operational schedule.
        </p>
      </section>

      {/* ── Opt-out choices ───────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Opt-out choices
        </h2>
        <p className="text-base text-text-secondary">
          SignalAF provides three distinct choices. These are clearly labeled
          — deleting history is not silently equivalent to deleting an
          account:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">1. Pause collection.</strong>{" "}
            Stop future submissions while preserving existing history until
            another choice is made.
          </li>
          <li>
            <strong className="text-text-primary">2. Delete history.</strong>{" "}
            Remove stored telemetry and derived history associated with the
            operator, revoke collection capability as needed, and retain only
            the minimum lawful deletion/audit record.
          </li>
          <li>
            <strong className="text-text-primary">3. Delete account.</strong>{" "}
            Delete the account link and associated operator data according to
            the retention policy.
          </li>
        </ul>
        <p className="text-sm text-text-muted">
          Until the Phase 5 controls are deployed, users should use the removal
          contact path. A future{" "}
          <code className="rounded bg-bg-elevated px-1 py-0.5 font-mono text-xs text-gold">
            data_opt_out
          </code>{" "}
          enforcement flag is planned; Phase 1 does not claim it is active.
        </p>
      </section>

      {/* ── Security model ────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Security model
        </h2>
        <p className="text-base text-text-secondary">
          SigRank defends submission integrity through multiple layers:
        </p>
        <ul className="flex flex-col gap-2 text-base text-text-secondary">
          <li>
            <strong className="text-text-primary">ed25519 signing:</strong>{" "}
            every snapshot is signed by the operator&apos;s device-bound key,
            generated locally at enrollment. The server verifies the signature
            before accepting. The board&apos;s{" "}
            <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
              source_attestations
            </code>{" "}
            table records signatures for audit.
          </li>
          <li>
            <strong className="text-text-primary">
              Server-side rescoring:
            </strong>{" "}
            the server recomputes all derived metrics from the four raw token
            pillars. Operators cannot submit inflated yield or leverage values
            directly.
          </li>
          <li>
            <strong className="text-text-primary">Replay protection:</strong>{" "}
            nonce tracking blocks resubmission of identical snapshots.
          </li>
          <li>
            <strong className="text-text-primary">
              Plausibility gates:
            </strong>{" "}
            implausible token ratios are flagged for review before appearing
            on the public board.
          </li>
          <li>
            <strong className="text-text-primary">
              Benford&apos;s Law check:
            </strong>{" "}
            aggregate leading-digit analysis flags statistical anomalies in
            token counts. A Benford flag is evidence for review, not proof of
            fabrication — it is considered alongside data coverage,
            independence, and collection behavior.
          </li>
        </ul>
        <p className="text-sm text-text-muted">
          Read tools need no auth — no API keys, no OAuth, no account needed
          to read the leaderboard or operator profiles. Enrollment requires a
          connect code from signalaf.com → Settings → New key; a codename
          alone is not enough for the signed/ranked path.
        </p>
      </section>

      {/* ── Privacy modes ─────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Privacy modes
        </h2>
        <p className="text-base text-text-secondary">
          Operators participate under a{" "}
          <strong className="text-text-primary">codename</strong> — a
          pseudonymous identifier chosen at enrollment. Your real identity is
          never required for the signed/ranked path; only the device public
          key and codename travel with each snapshot. Claimed operators may
          optionally link a codename to an account for profile features, but
          the submission payload itself remains pseudonymous.
        </p>
        <p className="text-base text-text-secondary">
          The paste path (
          <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
            submit_paste
          </code>
          ) is unsigned and goes through the web-paste endpoint with a codename
          only — but still sends only the four token counts, not the raw
          paste. Even if you paste mixed text (prose + numbers), only the
          extracted token counts are transmitted; the raw text never leaves
          your machine.
        </p>
      </section>

      {/* ── Enterprise review pack ────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          Enterprise review pack
        </h2>
        <p className="text-base text-text-secondary">
          Enterprise review materials — including the privacy model, data
          policy, consent model, retention schedule, and security architecture
          — are available for procurement and security review. Research,
          datasets, reports, and downloads use anonymized{" "}
          <code className="rounded bg-bg-elevated px-1.5 py-0.5 font-mono text-sm text-gold">
            signal-##########
          </code>{" "}
          identifiers and must not include direct identity fields. Contact the
          team for the enterprise review pack.
        </p>
      </section>

      {/* ── FAQ ───────────────────────────────────────────────────────── */}
      <section className="flex flex-col gap-3">
        <h2 className="font-mono text-xs uppercase tracking-[0.14em] text-text-dim">
          FAQ
        </h2>
        <dl className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              Does SigRank read my prompts or conversation content?
            </dt>
            <dd className="text-base text-text-secondary">
              No. The on-device scanner reads four token counts only — input,
              output, cache_read, and cache_create. No prompts, code, file
              contents, tool calls, or conversation text are ever transmitted,
              read, or stored by the SigRank service.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              What data leaves my machine when I submit a snapshot?
            </dt>
            <dd className="text-base text-text-secondary">
              Only four integer token counts plus submission metadata, the
              device public key, codename, window, and an ed25519 signature.
              The server verifies the signature and recomputes all derived
              metrics without ever seeing your data.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              Can I delete my data or opt out of collection?
            </dt>
            <dd className="text-base text-text-secondary">
              Yes. SignalAF provides three distinct choices: pause collection
              (stop future submissions, preserve history), delete history
              (remove telemetry and derived data), and delete account (remove
              the account link and associated data). Until Phase 5 controls
              are deployed, use the removal contact path.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              How does SigRank prevent leaderboard gaming?
            </dt>
            <dd className="text-base text-text-secondary">
              Every snapshot is ed25519-signed by a device-bound key. The
              server recomputes all derived metrics from the four raw token
              pillars — operators cannot submit inflated values directly.
              Replay protection blocks resubmission, plausibility gates flag
              implausible ratios, and Benford&apos;s Law analysis detects
              statistical anomalies.
            </dd>
          </div>
          <div className="flex flex-col gap-1">
            <dt className="font-semibold text-text-primary">
              Is the optional sigrank proxy a submission path?
            </dt>
            <dd className="text-base text-text-secondary">
              No. The optional sigrank proxy is a local loopback transport path
              to Anthropic or OpenAI, not a submission path to the SigRank
              leaderboard. When explicitly enabled, it necessarily receives and
              forwards provider-bound API keys, prompts, and responses in
              memory, but it does not persist that content or send it to the
              SigRank service — only provider-reported token counts are
              appended to a local file.
            </dd>
          </div>
        </dl>
      </section>

      {/* ── Cross-links ───────────────────────────────────────────────── */}
      <section className="mt-4 border-t border-bg-border-subtle pt-6">
        <p className="font-sans text-sm text-text-muted">
          Learn more:{" "}
          <Link
            href="/methodology"
            className="text-gold underline underline-offset-2"
          >
            Methodology
          </Link>
          {" · "}
          <Link
            href="/standard/open-vs-proprietary"
            className="text-gold underline underline-offset-2"
          >
            Open vs Proprietary
          </Link>
          {" · "}
          <Link
            href="/science"
            className="text-gold underline underline-offset-2"
          >
            Science
          </Link>
        </p>
      </section>
    </div>
  );
}
