/**
 * lib/board/static-board.ts — static all_time board reader.
 *
 * Reads the pre-generated static JSON snapshot of the all_time leaderboard
 * (public/data/board-all_time.json) and returns LeaderboardEntryWithPlatforms[]
 * — the same shape toEntry() produces. This eliminates the Supabase query that
 * pulled 2,184 rows (~2.5 MB) on every ISR cycle for /board/all, /research,
 * and /methodology.
 *
 * The static snapshot is generated by scripts/generate-board-snapshot.mjs
 * (run daily via GitHub Action or manually before deploy). 7d/30d/90d boards
 * stay LIVE via DB-side window-filtered queries (lib/board/queries.ts).
 *
 * Fallback: if the static file is missing or unreadable, returns an empty
 * array. The calling pages handle empty arrays gracefully (the board renders
 * empty, research/methodology show zeros).
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

export interface StaticBoardEntry {
  rank: number;
  percentile?: number | null;
  anonId: string;
  codename: string;
  subLabel?: string;
  isSeed?: boolean;
  location?: string;
  platform?: string;
  window?: string;
  signalClass: string;
  yield_?: number | null;
  leverage?: number | null;
  snr?: number;
  dev10x?: number | null;
  velocity?: number | null;
  totalTokens?: number | null;
  input?: number | null;
  output?: number | null;
  cacheWrite?: number | null;
  cacheRead?: number | null;
  scaleV?: number | null;
  costPerMillion?: number | null;
  efficiency?: number | null;
  opRatio?: string;
  snRatio?: number;
  messageVolume?: number;
  sessionDepth?: number;
  promptComplexity?: number;
  threadsRecalled?: number;
  compositeScore?: number;
  acctAge: string;
  lastSeen: string | null;
  status?: string | null;
  platforms?: string[];
  primaryDomain?: string;
}

interface StaticBoardFile {
  generated_at: string;
  window: string;
  total_operators: number;
  entries: StaticBoardEntry[];
}

let cached: StaticBoardEntry[] | null = null;

/**
 * Read the static all_time board snapshot.
 * Returns LeaderboardEntryWithPlatforms[] (same shape as toEntry() output).
 * Cached in memory after first read (module-level, survives warm invocations).
 */
export function getStaticAllTimeBoard(): StaticBoardEntry[] {
  if (cached) return cached;

  try {
    const filePath = join(process.cwd(), "public", "data", "board-all_time.json");
    const content = readFileSync(filePath, "utf8");
    const data: StaticBoardFile = JSON.parse(content);
    cached = data.entries ?? [];
    return cached;
  } catch {
    // File missing or unreadable — return empty (pages handle gracefully)
    return [];
  }
}

/** Clear the in-memory cache (for tests or after regeneration). */
export function clearStaticBoardCache(): void {
  cached = null;
}
